-- This just appear as an example without much context, included for completenesss
-- Sort showing errors, and not explicit types -> maybe need to specify which sort in newer versions, assuming my compiler defaults to Haskell2010...
-- Likely need to have more full examples to be able to figure out best way to set up toolchain for this book...

-- minima k xs = take k (sort xs)